### PR TITLE
Added Gravity.CENTER orientation

### PR DESCRIPTION
**Pull request by volser**
Gravity.CENTER

### CODE REVIEW

**Comment by douglasjunior** [comment]
Hi, thanks for contributing.

I could not understand why the CENTER? You want the Tooltip to appear in front of the component? Overriding?

**Comment by volser** [comment]
Yes, if I have big view I want to appear in front, because there no space on the some of sides

**Comment by douglasjunior** [comment]
I think this case should not be the arrow, because there is no where to point, right?

I'm testing your code now.. You could send a screenshot of an example?

**Comment by douglasjunior** [comment]
Otherwise, there should be an option to choose the direction of the arrow.

**Comment by volser** [comment]
yes, the arrow is not necessary

**Comment by douglasjunior** [comment]
Ok, I got it. Thanks.

**Pull request merged**
