### PR TITLE
feat (overlay): options to draw rectangle highlight or oval highlight

### PR DESCRIPTION
**Pull request by Singwai**

### CODE REVIEW

**Comment by Singwai** [comment]
image



This feature enable the to highlight exact rectangle shape of the anchoring view.
It give a more pleasant look when the anchoring view is very wide or long. See screenshot.

**Comment by douglasjunior** [comment]
Hi, thanks for contributing! 👍 

I think that constants `HIGHLIGHT_SHAPE_OVAL` and `HIGHLIGHT_SHAPE_RECTANGULAR` should to be in `OverlayView`.

Please, fix this before I merge the Pull Request.

**Comment by douglasjunior** [comment]
Please, check why Travis crash on the build: https://travis-ci.org/douglasjunior/android-simple-tooltip/builds/218951424

Before submit your commit, run the gradle check.
```bash
./gradlew build connectedCheck
```

**Comment by Singwai** [comment]
@douglasjunior  Take a look and let me know what you think and thank you for the quick response.

**Comment by douglasjunior** [comment]
Nice! Thanks!

**Pull request merged**
